# Profilo sviluppo
# Security aperta per test locale frontend/backend.

# Seed utente locale di test
app.seed.user.name=Test
app.seed.user.surname=User
app.seed.user.email=test@documind.local
app.seed.user.telephone=+391111111111
app.seed.user.password=test123

# URL del backend Python AI
app.python.url=http://localhost:5002

# Upload multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
